#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format code
npx prettier --write .

# Check for linting errors (if ESLint is set up)
npx eslint --fix ./src || (echo "ESLint failed, fix errors before committing" && exit 1)

# Verify the build works
npm run build --if-present || (echo "Build failed" && exit 1)